---
title: "Reviving a 27 Late2013 iMac"
author: "Bill Rice"
date: "10/11/2019"
htmlwidgets: yes
---

## How to get a little more life out of an old iMac

I like Apple products but they are hard to upgrade and when they are new they cost way too much money. I tend to get second hand Apple products just as they reach the end of their really useful life. I recently got an older 2013 (6 year old) 27 inch iMac. Great! Right? Well, it had 8gb of RAM and a 128GB SSD. 

Installing RAM in one of these machines is as simple as popping a panel off the back and putting the exact right kind of RAM into it... but the SSD is no simple task. There are really two headaches. How the heck do you get inside the iMac (the screen is GLUED to the chassis) and exactly what devices do you buy? The first problem is pretty simple for someone with the patience and steady hands. The website [iFixit](https://www.ifixit.com/Device/iMac_Intel_27%22_EMC_2639) has some wonderful instructions.

However, buying the parts is another headache. Get the wrong RAM and you will be tracking down kernel panics until you finally give up and toss the computer out a window. Get the wrong SSD or SSD adapter (more later) and you'll get a kernal panic every time you boot or return from sleep! I now have a 27 inch iMac with 1TB of storage and 32GB ram for under $300! I think I'll get another 2 years out of this giant desktop computer with a massive, beautiful screen.

What I finally did:
I purchased [this](https://amzn.to/32b2gcw) SPECIFIC adapter to let me plug a standard M.2 SSD into my mac

Purchased [this](https://amzn.to/2B2E3cL) SPECIFIC Intel 660P 1TB (2TB will also work) M.2 SSD

Purchased [this](https://amzn.to/2pY5hyG) SPECIFIC adhesive to reattach my screen

And upgraded with [this](https://amzn.to/316UTS7) SPECIFIC 32GB ram upgrade from OCW

Why was I so specific about all these items? Because Apple's never intended anybody to climb inside their computer and replace this stuff! They didn't really design it to be easy to work on or take standard parts. That special adapter I purchased above is only good for a handful of Mac computers.

